### ISSUE TITLE
TEM_notebook.ipynb

### ISSUE THREAD

**Issue by yanistazi** [jbakermans/torch_tem#1]
Hi,

Thank you so much for this implementation .

Is there a way we can reproduce the figures from TEM_notebook.ipynb from the original tensorflow implementation of the TEM? (we do not save the A_RNN.npy,... etc in torch implementation)

The test.py function does not have as many plots as the TEM notebook.

Yanis

**Comment by jbakermans** [comment]
Hi Yanis,
Indeed this version of TEM produces different plots compared to the tensorflow version. Currently, only the figures created in test.py are implemented - you could make your own plots using functionality in plot.py.
Using the functionality in TEM_notebook.ipynb is trickier. The pytorch and tensorflow versions of TEM are entirely separate implementations, and their input and output are not compatible. I'm afraid that you won't be able to plot pytorch TEM output using tensorflow TEM functions, and vice versa, directly from the current code. However, in principle both contain the same information and computation, so if you would reorganise pytorch variables in a way that is compatible with the tensorflow version's plotting functions, you could use TEM_notebook.ipynb for pytorch models. I'm not sure if I would recommend that - it's probably fiddly.
Hope that helps,
Jacob

**Comment by yanistazi** [comment]
Thank you Jacob, that is what I thought .

 Both have pros and cons . I have been working with both implementations and it seems like the Pytorch (yours) is much quicker to run given a  specific GPU and a specific number of iterations (I tried on T4,V100 and P100) . However, there are very interesting plots not available here (like the entorhinal and hippocampal cells plots) in the tensorflow implementation so I  will need to find a way to combine both (your plots are not present  the tensorflow implementation either).

Best,
Yanis

**Comment by jbakermans** [comment]
Interesting to hear about the GPU performance. Good luck!

**Comment by salimmj** [comment]
> Thank you Jacob, that is what I thought .
> 
> Both have pros and cons . I have been working with both implementations and it seems like the Pytorch (yours) is much quicker to run given a specific GPU and a specific number of iterations (I tried on T4,V100 and P100) . However, there are very interesting plots not available here (like the entorhinal and hippocampal cells plots) in the tensorflow implementation so I will need to find a way to combine both (your plots are not present the tensorflow implementation either).
> 
> Best, Yanis

I don't think it's straightforward to run this on GPU, were you able to do that?
