### ISSUE TITLE
inv_var_weight returns an inverse sigma, not a sigma

### ISSUE THREAD

**Issue by mrcslws** [jbakermans/torch_tem#2]
I noticed this while reading the code, not running it. Apologies if I'm missing something.

This implementation returns `sqrt(sum(1 / var))`. I think this should go through one more inversion, namely `1 / sqrt(sum(1 / var))`. The calling code expects it to be a sigma, not an inverse sigma.
https://github.com/jbakermans/torch_tem/blob/49c46ea825e2008760595fb36bda25190f69487f/utils.py#L28

The original tensorflow implementation inverted this sneakily by multiplying the log by -0.5 then taking the exp.
https://github.com/djcrw/generalising-structural-knowledge/blob/bead501bb26c6e2144362c5fecb95cdde9245fbf/tem_model.py#L122

**Comment by jbakermans** [comment]
You are absolutely right. Great catch, thanks for letting me know. Will fix asap.
- Edit: fixed now.
