### ISSUE TITLE
Clarification of envs/*x*json

### ISSUE THREAD

**Issue by RylanSchaeffer** [jbakermans/torch_tem#3]
Hi! Can you please clarify what each of the fields inside the `envs/*.json` files means? e.g. `n_locations`, `n_observations`, `n_actions`, `adjacency`, etc.

(Also, as a small side note, in case you don't know, you can create json files with structured indentation to make reading them easier)

**Comment by jbakermans** [comment]
Hi! Of course, happy to. The .json files define the environment that TEM operates on. These are essentially graphs, or more specifically MDPs. Each graph node is a location, and each location has an associated observation - that's the thing TEM is learning to predict. The graph edges are actions. Actions, like 'go-north', take TEM from one location to the other, and are provided as input for path integration.

At the highest level, the json file contains global information about the environment: `n_locations` the number of locations (graph nodes), `n_actions` the number of actions (north, east, south, and west in case of a grid graph), `n_observations` the number of possible observations associated to locations. `adjacency` contains a graph adjacency matrix, with a 1 if two nodes are adjacent and a 0 if not.

Then the `locations` list contains specific information about each graph node, or location. Each location has an `id`, an `observation`, `in_locations` locations from which it can be reached, `out_locations` locations that it can reach, and `in_degree` and `out_degree` the number of `in_locations` and `out_locations`. Then each location contains a list of all available actions `actions`.

The list of `actions` specifies the actions available at a location. Each action has a `probability` for taking that action (like a policy) and a `transition` probability distribution for next locations given that action.

I actually rarely read or write these json files manually (hence the lack of indentation :)), but I create them with a small matlab gui that I wrote for designing TEM environments - see image below. If you're interested I'm happy to share the code. The environment files are read to generate input data, consisting of observations and actions, for TEM.

Let me know if that helps!

<img width="898" alt="image" src="https://user-images.githubusercontent.com/23357015/161077508-7e5a5f89-ace6-44ab-8411-aa1ea15a6863.png">

**Comment by RylanSchaeffer** [comment]
Wow thanks for the great response! Could you share that MATLAB code?  I would hate to design one of these environments myself by editing one of your JSON files :)

**Comment by jbakermans** [comment]
Yes I would definitely not recommend the manual route :) I've made the Matlab GUI repo public, see https://github.com/jbakermans/WorldBuilder. I'll close this now - if you have any trouble with the GUI, let me know there.
