### ISSUE TITLE
Appropriate length to train for?

### ISSUE THREAD

**Issue by RylanSchaeffer** [jbakermans/torch_tem#4]
I saw in the code that `train_it` is around 20k, but the losses all appear to converge after ~10k:

![image](https://user-images.githubusercontent.com/8942987/161580433-0a1ffa98-658d-4cc6-a1f2-4d69eb3db541.png)

How long do you recommend training for? Is 20k necessary or recommended?

**Comment by jbakermans** [comment]
Hi! Agree that the losses and performance mostly converge before the full training length. The reason to keep training for a a bit longer is usually that representations might still change; I noticed that sometimes to get beautiful grid cells, I need to train a bit longer after the losses seem to plateau. Feel free to play around with it!

**Comment by RylanSchaeffer** [comment]
Thank you! You are so good at providing prompt, useful answers :)

**Comment by RylanSchaeffer** [comment]
Are you in Tim Behrens lab, by the way?

**Comment by jbakermans** [comment]
Thanks! And yes :)

**Comment by RylanSchaeffer** [comment]
I'm going to shoot you an email

**Comment by RylanSchaeffer** [comment]
One follow up question: should the number of training iterations increase with the environment size? e.g. if I train with the 10x10 env, should I train for 10 or 100 times longer?

**Comment by jbakermans** [comment]
Larger envs indeed do need more training iterations. I'm not exactly sure how these parameters scale - mostly an empirical question, probably easiest to just give it a try.
